# Generated by Django 2.2 on 2021-12-04 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('c_time',)},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_author',
            new_name='c_author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_content',
            new_name='c_content',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_time',
            new_name='c_time',
        ),
    ]
