# Generated by Django 2.2 on 2021-12-04 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20211204_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='c_article',
        ),
    ]
