# Generated by Django 2.2 on 2021-11-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='view_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
