# Generated by Django 2.2 on 2021-11-30 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_blogarticle_view_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogarticle',
            old_name='view_amount',
            new_name='view_count',
        ),
    ]
