# Generated by Django 2.2 on 2021-12-04 03:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0001_initial'),
        ('article', '0004_auto_20211201_1658'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blogArticle',
            new_name='Article',
        ),
    ]
