# Generated by Django 2.2 on 2021-12-04 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20211203_2100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-a_created_time',)},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='author',
            new_name='a_author',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='a_content',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='created_time',
            new_name='a_created_time',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='a_title',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='topic',
            new_name='a_topic',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='updated_time',
            new_name='a_updated_time',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='view_count',
            new_name='a_view_count',
        ),
    ]
