# Generated by Django 2.2 on 2021-12-04 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20211203_2106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-created_time',)},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='a_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='a_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='a_created_time',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='a_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='a_topic',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='a_updated_time',
            new_name='updated_time',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='a_view_count',
            new_name='view_count',
        ),
    ]
