# Generated by Django 2.2 on 2021-12-04 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20211203_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='author',
            new_name='a_author',
        ),
    ]
