# Generated by Django 2.2 on 2021-12-04 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20211204_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='a_content',
        ),
    ]
