# Generated by Django 2.2 on 2021-12-04 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20211204_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articletopic',
            old_name='a_created_time',
            new_name='created_time',
        ),
    ]
