# Generated by Django 2.2 on 2021-12-04 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_auto_20211204_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='view_count',
            new_name='a_view_count',
        ),
    ]
