# Generated by Django 2.2 on 2021-12-04 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_auto_20211204_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articletopic',
            old_name='created_time',
            new_name='t_created_time',
        ),
    ]
