# Generated by Django 2.2 on 2021-12-04 20:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0018_auto_20211204_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='a_modified_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
