# Generated by Django 2.2 on 2021-12-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0020_auto_20211204_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='a_created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='articletopic',
            name='t_created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
